[package]
name = "habit-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
directories = "6.0.0"
iced = "0.14.0"
serde = { version = "1.0.228", features = [ "derive" ] }
serde_json = "1.0.149"
time = { version = "0.3.47", features = [ "serde", "formatting", "parsing" ] }
